import type { Metadata } from 'next';
import './globals.css';
import { chivo, work_sans } from '@/src/shared/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${chivo} ${work_sans}`}>{children}</body>
    </html>
  );
}
