import type { Metadata } from 'next';
import { Chivo, Work_Sans } from 'next/font/google';
import './globals.css';

const chivo_init = Chivo({
  subsets: ['latin'],
  // extralight, medium, bold
  weight: ['200', '500', '700'],
  variable: '--font-chivo',
});

const work_sans_init = Work_Sans({
  subsets: ['latin'],
  // extralight, medium, extrabold
  weight: ['200', '500', '800'],
  variable: '--font-work-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${chivo_init.variable} ${work_sans_init.variable}`}>
        {children}
      </body>
    </html>
  );
}
